[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heed = "0.20.0-alpha.4"
ord = { git = "https://github.com/hxuchen/ord.git", branch = "inscriber" }